from baseflow.methods.Boughton import *
from baseflow.methods.Chapman import *
from baseflow.methods.CM import *
from baseflow.methods.Eckhardt import *
from baseflow.methods.EWMA import *
from baseflow.methods.Fixed import *
from baseflow.methods.Furey import *
from baseflow.methods.LH import *
from baseflow.methods.Local import *
from baseflow.methods.Slide import *
from baseflow.methods.UKIH import *
from baseflow.methods.Willems import *
